GET http://localhost:3001/api/persons

###
GET https://sheltered-shelf-77221.herokuapp.com/api/persons


###
DELETE http://localhost:3001/api/persons/610e2382b779a22e64a6fec6



###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "S",
  "number": "045-2177225"
}



###
PUT http://localhost:3001/api/persons/610e4b1a2705255b89be7e75
Content-Type: application/json

{
  "name": "Luniva Hyoju",
  "number": "0466137328"
}